[project]
name = "gki-kernel-builder"
version = "0.1.0"
description = "A simple python gki kernel builder"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "basedpyright>=1.29.4",
    "pre-commit>=4.2.0",
    "requests>=2.32.4",
    "rich>=14.0.0",
    "ruff>=0.12.0",
]

[tool.basedpyright]
include = ["src"]
typeCheckingMode = "recommended"
reportUnusedCallResult = "none"
reportAny = "none"
reportExplicitAny = "none"
