name: Kernel Builder
permissions:
  contents: write
  actions: write

on:
  workflow_call:
    inputs:
      KSU:
        type: string
        required: true
      SUSFS:
        type: string
        required: true
      LXC:
        type: string
        required: true
      VERBOSE:
        type: string
        required: true

  workflow_dispatch:
    inputs:
      KSU:
        description: "KernelSU variant"
        default: "NONE"
        type: choice
        options: ["NONE", "NEXT", "SUKI", "RKSU"]

      SUSFS:
        description: "Enable SUSFS"
        default: "false"
        type: choice
        options: ["false", "true"]

      LXC:
        description: "Enable LXC"
        default: "false"
        type: choice
        options: ["false", "true"]

      VERBOSE:
        description: "Enable verbose output"
        default: "false"
        type: choice
        options: ["false", "true"]
env:
  RICH_FORCE_COLOR: true
  FORCE_COLOR: "1"
  TTY_COMPATIBLE: "1"
  TERM: xterm-256color

jobs:
  default:
    runs-on: ubuntu-latest

    steps:
      - name: Fail SUSFS requirement check
        if: ${{ inputs.SUSFS == 'true' && inputs.KSU == 'NONE' }}
        run: |
          echo "Cannot use SUSFS without KernelSU"
          exit 1

      - name: Checkout code & init submodules
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: astral-sh/setup-uv
        uses: astral-sh/setup-uv@v6.3.1
        with:
          python-version: '3.12'
          enable-cache: true
          cache-suffix: "gki-builder"
          cache-dependency-glob: |
            **/pyproject.toml
            **/uv.lock

      - name: Create venv & Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq bc bison ccache curl flex git tar wget aria2

          uv venv
          uv sync --frozen --no-install-project

      - name: Build
        id: setup-env
        env:
          KSU: ${{ inputs.KSU }}
          SUSFS: ${{ inputs.SUSFS }}
          LXC: ${{ inputs.LXC }}
          VERBOSE_OUTPUT: ${{ inputs.VERBOSE }}
        run: |
          export PYTHONPATH=$(pwd)
          uv run python kernel_builder/main.py

      - name: Upload final artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ESK${{ steps.setup-env.outputs.variant }}
          path: |
            ${{ steps.setup-env.outputs.output }}/ESK-${{ steps.setup-env.outputs.version }}${{ steps.setup-env.outputs.variant }}-AnyKernel3.zip
            ${{ steps.setup-env.outputs.output }}/ESK-${{ steps.setup-env.outputs.version }}${{ steps.setup-env.outputs.variant }}-boot.img
