name: Run tests and upload coverage

on:
  push

permissions:
  contents: read

jobs:
    test:
      name: Run tests and collect coverage
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            fetch-depth: 2

        - name: astral-sh/setup-uv
          uses: astral-sh/setup-uv@v6.4.1
          with:
            python-version: '3.12'
            enable-cache: true
            cache-suffix: "gki-builder"
            cache-dependency-glob: |
              **/pyproject.toml
              **/uv.lock

        - name: Install dependencies
          run: uv sync --frozen --no-install-project

        - name: Run tests
          run: PYTHONPATH=$(pwd) uv run pytest --cov --cov-branch --cov-report=xml

        - name: Upload results to Codecov
          uses: codecov/codecov-action@v5
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
