name: Multi Variants Builder
permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        variant:
          - { name: "Non-KSU", KSU: "NONE", LXC: "false"}
          - { name: "Non-KSU+LXC", KSU: "NONE", LXC: "true"}
          - { name: "KSUN", KSU: "NEXT", LXC: "false" }
          - { name: "KSUN+LXC", KSU: "NEXT", LXC: "true" }
          - { name: "SUKISU", KSU: "SUKI", LXC: "false" }
          - { name: "SUKISU+LXC", KSU: "SUKI", LXC: "true" }
    name: Build ${{ matrix.variant.name }} variant
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      KSU: ${{ matrix.variant.KSU }}
      LXC: ${{ matrix.variant.LXC }}