name: Pre-commit
permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: 🔍 Checkout code & init submodules
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run pre-commit hook
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files

      - name: Commit & push fixes
        if: github.repository_owner == github.actor
        uses: stefanzweifel/git-auto-commit-action@v6.0.1
        with:
          commit_message: "[skip ci] style(src): pre-commit hook"
