name: Pre-commit
permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 1

      - name: astral-sh/setup-uv
        uses: astral-sh/setup-uv@v6.3.1
        with:
          python-version: '3.12'
          enable-cache: true
          cache-suffix: "gki-builder"
          cache-dependency-glob: |
            **/pyproject.toml
            **/uv.lock

      - name: Create venv & Install dependencies
        run: |
          uv venv
          uv sync

      - name: Run pre-commit hook
        run: uv run pre-commit run --all-files --show-diff-on-failure --color=always || true

      - name: Commit & push fixes
        if: github.repository_owner == github.actor
        uses: stefanzweifel/git-auto-commit-action@v6.0.1
        with:
          commit_message: "[skip ci] style(src): pre-commit hook"
